import '@radix-ui/themes/styles.css';
import './theme-config.css'
import './globals.css'
import Navbar from './Navbar'
import { Inter } from 'next/font/google'
import { Theme, ThemePanel } from '@radix-ui/themes';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <Theme appearance="light" accentColor="violet">
          <Navbar />
          <main className='px-8 py-4'>
            {children}
          </main>
          {/* <ThemePanel /> */}
        </Theme>
      </body>
    </html>
  )
}
