import '@radix-ui/themes/styles.css';
import Navbar from './Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import { Theme } from '@radix-ui/themes';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="cupcake">
      <body className={inter.className}>
        <Theme>
          <Navbar />
          <main>
            {children}
          </main>
        </Theme>
      </body>
    </html>
  )
}
